[package]
name = "x12-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
x12-types = { path = "../x12/276-277-support" }
tabular = "0.2"
clap = { version = "4.5.37", features = [ "derive"] }
serde = "1"
serde_json = "1"
csv = "1.3.1"

pretty_env_logger = "0.5"
log = "0.4.27"